// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkKhwfKH5XyMwdkgWV87SWUlEXE7BZA3k',
    appId: '1:213971425257:web:e17949cd71236f7b5f1d78',
    messagingSenderId: '213971425257',
    projectId: 'chatapp-8ad35',
    authDomain: 'chatapp-8ad35.firebaseapp.com',
    storageBucket: 'chatapp-8ad35.firebasestorage.app',
    measurementId: 'G-VC290SRY3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBlm3uBAV-a_AJmYwjCOwgjKdTkRqq1Z0',
    appId: '1:213971425257:android:62facb3bec0175c45f1d78',
    messagingSenderId: '213971425257',
    projectId: 'chatapp-8ad35',
    storageBucket: 'chatapp-8ad35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNG7dO3lvJQmDL5ZTgzLg7X2exLWO5OQU',
    appId: '1:213971425257:ios:f12d59acf8e5d6d85f1d78',
    messagingSenderId: '213971425257',
    projectId: 'chatapp-8ad35',
    storageBucket: 'chatapp-8ad35.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNG7dO3lvJQmDL5ZTgzLg7X2exLWO5OQU',
    appId: '1:213971425257:ios:f12d59acf8e5d6d85f1d78',
    messagingSenderId: '213971425257',
    projectId: 'chatapp-8ad35',
    storageBucket: 'chatapp-8ad35.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkKhwfKH5XyMwdkgWV87SWUlEXE7BZA3k',
    appId: '1:213971425257:web:d15551f3d33663885f1d78',
    messagingSenderId: '213971425257',
    projectId: 'chatapp-8ad35',
    authDomain: 'chatapp-8ad35.firebaseapp.com',
    storageBucket: 'chatapp-8ad35.firebasestorage.app',
    measurementId: 'G-BY9P3NQTDQ',
  );

}